# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0’
pod 'MagicalRecord'
pod 'CZPicker'
pod 'FastEasyMapping', '~> 1.0.1'
pod 'netfox'
pod 'SVProgressHUD'
target 'MultiClub' do

end

